apiVersion: v2
name: example
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
dependencies:
  - name: example
    repository: oci://123456789012.dkr.ecr.eu-central-1.amazonaws.com
    version: 0.1.0
