apiVersion: v1
data:
  enableOCI: dHJ1ZQo= # true
  name: bXlyZXBvLmV4YW1wbGUuY29tCg== # example-repo
  type: aGVsbQo= # helm
  url: MTIzNDU2Nzg5MDEyLmRrci5lY3IuZXUtY2VudHJhbC0xLmFtYXpvbmF3cy5jb20K # 123456789012.dkr.ecr.eu-central-1.amazonaws.com
  username: YWRtaW4= # admin
  password: MWYyZDFlMmU2N2Rm # 1f2d1e2e67df
kind: Secret
metadata:
  labels:
    argocd-ecr-updater: enabled
    argocd.argoproj.io/secret-type: repository
  name: example
