apiVersion: v1
kind: Secret
stringData:
  enableOCI: true
  name: helm-ecr # can be anything
  type: helm
  url: 123456789012.dkr.ecr.eu-central-1.amazonaws.com
  username: AWS
  password: ""
metadata:
  labels:
    argocd-ecr-updater: enabled
    argocd.argoproj.io/secret-type: repository
  name: example
