apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "argocd-ecr-updater.fullname" . }}
  labels:
    {{- include "argocd-ecr-updater.labels" . | nindent 4 }}
data:
  ARGOCD_ECR_UPDATER_NAMESPACE: {{ .Values.env.namespace | quote }}
  {{- range $key, $val := .Values.env.additionalEnv }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
