name: helm-test
on:
  pull_request:
    branches:
      - main
    paths:
      - charts/**
      - .github/workflows/helm-test.yaml

permissions: read-all

jobs:
  helm-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - name: Unshallow
        run: git fetch --prune --unshallow

      - uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # v4.7.0
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@e8788873172cb653a90ca2e819d79d65a66d4e76 # v2.4.0

      - name: Run chart-testing (lint)
#        run: ct lint --target-branch=main --check-version-increment=false
        run: ct lint --check-version-increment=false --charts charts/argocd-ecr-updater
